version: "3.9"
services:
  redis:
    image: redis:7.2.4-alpine3.19
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 20s
      retries: 100
  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5673:5673"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth_postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postsAuth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postsAuth -U root"]
      interval: 5s
      timeout: 20s
      retries: 100

  auth_api:
    build:
      context: ../posts-auth
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_SOURCE=postgresql://root:secret@auth_postgres:5432/postsAuth?sslmode=disable
      - REDIS_URL=redis:6379
      - RBM_URL=amqp://user:password@rabbitmq:5672/
      - REDIS_DB_NUMBER=1
      - SERVER_ADDRESS=0.0.0.0:8081
    depends_on:
      auth_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]

  posts_postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postsPosts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postsPosts -U root"]
      interval: 5s
      timeout: 20s
      retries: 100

  posts_api:
    build:
      context: ../posts-post
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_SOURCE=postgresql://root:secret@posts_postgres:5432/postsPosts?sslmode=disable
      - REDIS_URL=redis:6379
      - RBM_URL=amqp://user:password@rabbitmq:5672/
      - REDIS_DB_NUMBER=2
      - SERVER_ADDRESS=0.0.0.0:8082
    depends_on:
      posts_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]

  gateway_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - AUTH_GRPC_SERVICE=auth_api:8081
      - POSTS_GRPC_SERVICE=posts_api:8082
      - SERVER_ADDRESS=0.0.0.0:8080
      - ENVIRONMENT=dev
    depends_on:
      auth_api:
        condition: service_started
      posts_api:
        condition: service_started
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]
